import fs from "node:fs";
import path from "node:path";
import { repoRoot } from "./paths.mjs";
import { loadPackageCatalog } from "./package-catalog.mjs";

const AUDIT_REL = "docs/internal/skill-invocation-audit.md";
const AUDIT_PATH = path.join(repoRoot, AUDIT_REL);
const GENERATED_MARKER = "<!-- Generated by `roborepo skill audit`; edit package config or skill metadata instead. -->";

function readSkill(entry) {
  const filePath = path.join(entry.sourcePath, "SKILL.md");
  const content = fs.readFileSync(filePath, "utf8").replace(/\r\n/g, "\n");
  const parsed = parseFrontmatter(content);
  return { name: entry.id, filePath, content, policy: entry.policy, ...parsed };
}

function parseFrontmatter(content) {
  const match = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(content);
  if (!match) return { meta: {}, body: content };
  return { meta: parseYamlish(match[1]), body: match[2] };
}

function parseYamlish(frontmatter) {
  const lines = frontmatter.split("\n");
  const meta = {};
  for (let i = 0; i < lines.length; i += 1) {
    const m = /^([A-Za-z0-9_-]+):(?:\s*(.*))?$/.exec(lines[i]);
    if (!m) continue;
    const [, key, raw = ""] = m;
    if (raw === ">" || raw === "|") {
      const block = [];
      while (i + 1 < lines.length && /^(?:\s{2,}|\t)/.test(lines[i + 1])) {
        i += 1;
        block.push(lines[i].replace(/^(?:\s{2}|\t)/, ""));
      }
      meta[key] = block.join(raw === ">" ? " " : "\n").trim();
    } else {
      meta[key] = raw.replace(/^["']|["']$/g, "").trim();
    }
  }
  return meta;
}

function manifestPolicies() {
  return new Map(packageSkillEntries().map((entry) => [entry.id, entry.policy]));
}

function packageSkillEntries() {
  return loadPackageCatalog({ includeUnavailable: true }).flatMap((pkg) =>
    (pkg.resources || [])
      .filter((resource) => resource.type === "skill")
      .map((resource) => ({
        id: resource.id,
        sourcePath: path.join(pkg.sourceRoot, resource.source),
        policy: {
          skill: resource.id,
          risk: resource.risk || "medium",
          invocation: resource.invocation,
          explicit_command: (resource.entrypoints || []).some((entrypoint) => entrypoint.type === "slash-command"),
        },
      }))
  );
}

function findings(skill, knownSkillNames = []) {
  const out = [];
  const frontmatter = skill.content.startsWith("---\n")
    ? skill.content.slice(4, skill.content.indexOf("\n---\n", 4))
    : "";
  const unsupported = ["disable-model-invocation", "allowed-tools", "tools", "shell"].filter((key) =>
    Object.prototype.hasOwnProperty.call(skill.meta, key),
  );
  if (unsupported.length) out.push(`frontmatter: ${unsupported.join(", ")}`);
  if (/^!\s*\S/m.test(skill.body)) out.push("dynamic shell line");
  if (/```(?:bash|sh|shell)\s+!/i.test(skill.body)) out.push("dynamic shell code block");
  if (/\b(git push|deploy|release|publish|rm -rf|curl\s|wget\s)\b/i.test(skill.body)) out.push("side-effect keyword");
  if (!String(skill.meta.description || "").trim()) out.push("missing trigger description");
  out.push(...referenceReachability(skill));
  out.push(...pairedSkillShape(skill, knownSkillNames));
  return out;
}

// Vague conditions in a `Load when` cell. Each of these hands the judgment back to the reader, who
// is the party that did not already know the skill applied — so the pairing silently never fires.
const VAGUE_TRIGGERS = /\b(when relevant|if relevant|as needed|when appropriate|if useful|when useful|as applicable|when it makes sense)\b/i;

// Structural check on a skill's paired-skill declaration.
//
// A paired skill is loaded from beside a skill the way a reference is loaded from within one, and
// it fails the same way: by being mentioned rather than required. Prose that names a related skill
// without instructing the load reads as background, and the observed consequence is that the user
// names the paired skill by hand on every request.
//
// Reported here, all structural:
//   - a skill that names another skill in prose but declares no Paired Skills table;
//   - a table that does not instruct the load;
//   - a `Load when` cell whose condition is not checkable ("when relevant");
//   - a trigger that fires on the user asking, which restores the manual step being removed.
//
// What is NOT judged: whether a given pairing is the right one. That is a claim about the skills'
// subject matter, not about the shape of the declaration.
function pairedSkillShape(skill, knownSkillNames = []) {
  const table = /## Paired Skills\n([\s\S]*?)(?=\n## |\n$)/.exec(skill.body);
  if (!table) {
    // Only flag skills that already tell the reader to pair with something; a skill with no
    // cross-skill relationship is not missing a table.
    //
    // "pair with" was the only phrasing caught originally, which let the same instruction slip
    // through as "Use `code-style`" or "load `plan-write`". The verb list is broader now, but the
    // target must be a *known skill name*: backticks around an ordinary value ("Use `data-testid`",
    // "Use `blocked`") is not a pairing, and matching any backticked token flagged both of those.
    const others = knownSkillNames.filter((name) => name !== skill.name);
    const prosePairing = others.length
      ? new RegExp(`\\b(?:pair(?: it)? with|load|use|read) \`(?:${others.join("|")})\``, "i")
      : /\bpair with `[a-z-]+`/i;
    return prosePairing.test(skill.body)
      ? ["names a paired skill in prose but declares no Paired Skills table"]
      : [];
  }

  const out = [];
  const body = table[1];
  if (!/do not wait to be asked for them by name/i.test(body)) {
    out.push("Paired Skills table does not instruct the load");
  }

  const rows = body.split("\n").filter((line) => /^\|/.test(line) && !/^\|\s*-+/.test(line)).slice(1);
  const vague = [];
  const requestGated = [];
  for (const row of rows) {
    const cells = row.split("|").map((cell) => cell.trim());
    const [, name, when = ""] = cells;
    if (!name || !when) continue;
    if (VAGUE_TRIGGERS.test(when)) vague.push(name);
    if (/\bthe user (asks|requests|requested|names)\b/i.test(when)) requestGated.push(name);
  }
  if (vague.length) out.push(`unresolvable paired-skill trigger: ${vague.join(", ")}`);
  if (requestGated.length) out.push(`paired-skill trigger gated on a user request: ${requestGated.join(", ")}`);
  return out;
}

// The artifact-producing mode, by convention. A skill whose named modes include `write` or `create`
// produces something a user keeps; every other mode inspects or routes.
const ARTIFACT_MODES = ["write", "create"];

// Structural check on a skill's own mode/reference matrix.
//
// Two failures are reported. The first is a reference that some named mode requires but the
// artifact-producing mode cannot reach: a mandatory finishing step parked behind a mode nobody has
// to select is a step the artifact path never takes. The second is a matrix that no longer parses,
// which matters because the routing tests read this same prose — prose that stops parsing would
// otherwise yield an empty reference set that passes every assertion trivially.
//
// This stays structural on purpose. Whether a reference *should* be required is a judgment about
// the skill's content; whether a mode can reach one it declares elsewhere is not.
function referenceReachability(skill) {
  // A mode-taking skill lists references per named mode; a mode-free skill such as plan-write lists
  // them per situation. Both lists share one bullet shape and the same reachability rule.
  const section = /(?:For a named mode, read only the needed references|Read the references for the situation):\n([\s\S]*?)\n\n/.exec(skill.body);
  if (!section) {
    // Only skills that declare modes are expected to carry a matrix; a single-purpose skill with
    // no mode list is not missing anything.
    return /^\/\S+ (write|create|review|validate)\b/m.test(skill.body) ? ["unparseable mode/reference matrix"] : [];
  }

  const matrix = new Map();
  for (const bullet of section[1].split(/\n(?=- )/)) {
    const mode = /^- `([a-z-]+)`[:,]/.exec(bullet.replace(/\s+/g, " ").trim());
    if (!mode) continue;
    matrix.set(mode[1], [...bullet.matchAll(/references\/[a-z0-9-]+\.md/g)].map((match) => match[0]));
  }
  if (!matrix.size) return ["unparseable mode/reference matrix"];

  const artifactMode = ARTIFACT_MODES.find((mode) => matrix.has(mode));
  if (!artifactMode) return [];

  const reachable = new Set(matrix.get(artifactMode));
  const unreachable = [...matrix]
    .filter(([mode]) => mode !== artifactMode)
    .flatMap(([, references]) => references)
    .filter((reference) => !reachable.has(reference) && isCompletionReference(reference));
  return unreachable.length
    ? [`reference unreachable from \`${artifactMode}\`: ${[...new Set(unreachable)].join(", ")}`]
    : [];
}

// Not every reference belongs to every mode — `workflow-update.md` is `update`'s business alone, and
// requiring it from `create` would be noise. The finding targets references that define how work is
// finished or graded, which is the class that must be reachable from the mode producing the
// artifact.
function isCompletionReference(reference) {
  return /(review-loop|validat|completion|checklist)/.test(reference);
}

function recommendation(policy, skillFindings) {
  if (!policy) return "Add manifest policy.";
  if (skillFindings.some((item) => item.includes("dynamic shell") || item.includes("frontmatter"))) {
    return "Review before allowing implicit invocation.";
  }
  if (policy.risk === "high" || policy.invocation === "manual") return "Keep manual-only or command-gated.";
  if (policy.risk === "medium") return "Keep trigger narrow; add near-miss tests.";
  return "Keep auto if trigger remains narrow.";
}

function escapeCell(value) {
  return String(value ?? "").replaceAll("|", "\\|").replace(/\s+/g, " ").trim();
}

export function renderSkillAudit() {
  const policies = manifestPolicies();
  const skills = packageSkillEntries().map(readSkill);
  // Prose-pairing detection matches against real skill names, so an ordinary backticked value is
  // never mistaken for a cross-skill instruction.
  const knownSkillNames = skills.map((entry) => entry.name).filter(Boolean);
  const rows = skills.map((skill) => {
    const policy = policies.get(skill.name);
    const skillFindings = findings(skill, knownSkillNames);
    return {
      skill: skill.name,
      invocation: policy?.invocation || "missing",
      risk: policy?.risk || "missing",
      explicit: policy ? String(policy.explicit_command) : "missing",
      findings: skillFindings.length ? skillFindings.join("; ") : "none",
      recommendation: recommendation(policy, skillFindings),
    };
  });

  const unknownPolicies = [...policies.keys()].filter((name) => !skills.some((skill) => skill.name === name));
  const dynamicCount = rows.filter((row) => row.findings !== "none").length;

  return `${[
    "# Skill Invocation Audit",
    "",
    GENERATED_MARKER,
    "",
    "## Summary",
    "",
    `- Shared skills: ${skills.length}`,
    `- Package skill resources: ${policies.size}`,
    `- Static findings: ${dynamicCount}`,
    unknownPolicies.length ? `- Unknown manifest entries: ${unknownPolicies.join(", ")}` : "- Unknown manifest entries: none",
    "",
    "## Compatibility Result",
    "",
    "Claude and Codex express manual-only skill behavior in different metadata locations.",
    "Keep shared `SKILL.md` frontmatter portable; use package-backed checks before adding harness-specific manual-only fields.",
    "",
    "| Harness | Manual-only setting | Source |",
    "| --- | --- | --- |",
    "| Claude | `disable-model-invocation: true` | `SKILL.md` frontmatter |",
    "| Codex | `policy.allow_implicit_invocation: false` | `agents/openai.yaml` |",
    "",
    "## Current Shared Skills",
    "",
    "| Skill | Invocation | Risk | Explicit command | Static findings | Recommendation |",
    "| --- | --- | --- | --- | --- | --- |",
    ...rows.map((row) =>
      `| \`${escapeCell(row.skill)}\` | ${escapeCell(row.invocation)} | ${escapeCell(row.risk)} | ${escapeCell(row.explicit)} | ${escapeCell(row.findings)} | ${escapeCell(row.recommendation)} |`
    ),
    "",
    "## Static Checks",
    "",
    "The audit flags:",
    "",
    "- harness-specific or broad tool-grant frontmatter",
    "- dynamic shell lines",
    "- dynamic shell code-block hints",
    "- side-effect keywords that deserve manual review",
    "- missing trigger descriptions",
    "- completion references a mode requires but the artifact-producing mode cannot reach",
    "- mode/reference matrices that no longer parse",
    "- paired skills mentioned in prose but never declared, or declared without instructing the load",
    "- paired-skill triggers that are unresolvable (\"when relevant\") or gated on a user request",
    "",
    "## Next Actions",
    "",
    "1. Add trigger tests for expected matches and near misses, starting with medium-risk skills.",
    "2. Add manual-only rendering/checks only when a skill is intentionally converted away from implicit invocation.",
    "3. Keep high-risk or side-effecting workflows behind explicit commands or hooks.",
    "",
  ].join("\n")}\n`;
}

export function skillAudit(args = []) {
  const checkOnly = args.includes("--check");
  const write = args.includes("--write") || !checkOnly;
  const content = renderSkillAudit();
  const current = fs.existsSync(AUDIT_PATH) ? fs.readFileSync(AUDIT_PATH, "utf8").replace(/\r\n/g, "\n") : "";

  if (checkOnly) {
    if (current === content) {
      console.log(`ok: ${AUDIT_REL}`);
      return;
    }
    console.error(`stale: ${AUDIT_REL} (run roborepo skill audit)`);
    process.exit(1);
  }

  if (write) {
    fs.writeFileSync(AUDIT_PATH, content);
    console.log(`render: ${AUDIT_REL}`);
  }
}
